apiVersion: apps/v1
kind: Deployment
metadata:
  name: resturant-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resturant-service
  template:
    metadata:
      labels:
        app: resturant-service
    spec:
      containers:
      - name: resturant-service
        image: resturant-service:latest
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: resturant-service
spec:
  selector:
    app: resturant-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
---
# Repeat similar configuration for api-gateway and restaurant-service